replicaCount: 1

image:
  repository: quay.apps.ocp4-8.infocepo.com/ministere-interieur-prj-plec/app-nginx-static-demo
  pullPolicy: Always
  tag: "master"

imagePullSecrets: 
  - name: "quay-image-pull-secret"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  secret:
    enabled: true
  host: dso-demo-static-helm.apps.ocp4-8.infocepo.com
  tls:
    secretName: dso-demo-static-tls

resources: 
  limits:
    memory: "256Mi"
    cpu: "500m"  
  requests:
    memory: "256Mi"
    cpu: "500m"  

